/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IntegratedJumplistGenerator_2;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;
import static java.lang.Integer.parseInt;
import javax.swing.filechooser.FileNameExtensionFilter;

public class IntegratedJumplistGeneratorVer69 extends javax.swing.JFrame {

    public StringBuilder sb = new StringBuilder(64);
    private final String boilerplate
            = "<html>\n"
            + "<head>\n"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale-1.0\">"
            + "\n<link href=\"style.css\" rel=\"stylesheet\"/>\n"
            + "\n<link href=\"tf_navicon.css\" rel=\"stylesheet\"/>\n"
            + "<title>"
            + "Ultimate HTML Editor 3000"
            + "</title>\n"            
            + "</head>\n"
            + "<body>\n"
            + "<nav class=\"links\">\n"
            + "\n<a id=\"navicon\" href=\"#\"><img src=\"tf_navicon.png\" alt=\"\" /></a>\n"
            + "\n<ul>"
            + "</ul>\n</nav>\n"
            + "<div class=\"pics\">\n"
            + "</div>\n"
//            + "<body>\n"
////            + "<select onChange=\"location.href=this[selectedIndex].value\">\n"
////            + "<option value=\"\">default</option>\n"
////            + "</select>\n"
            + "\n</body>\n"
            + "</html>";

    /**
     * Creates new form IntegratedJumplistGeneratorVer69
     */
    public IntegratedJumplistGeneratorVer69() {
        initComponents();
        txtDoc.setText(boilerplate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        btnAddtitle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDisplay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnAddlinks = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNumCols = new javax.swing.JTextField();
        btnAddTable = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNumRows = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        imgURL = new javax.swing.JTextField();
        imgname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnAddonlineimg = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnBrowse1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnBrowsevideo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDoc = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Page Title");

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        btnAddtitle.setText("Add Page Title");
        btnAddtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 381, Short.MAX_VALUE)
                        .addComponent(btnAddtitle)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAddtitle))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Title", jPanel10);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Display Text");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("URL");

        btnAddlinks.setText("Add Option");
        btnAddlinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddlinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUrl)
                            .addComponent(txtDisplay)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 395, Short.MAX_VALUE)
                        .addComponent(btnAddlinks)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btnAddlinks))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Links", jPanel1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Number of Columns");

        btnAddTable.setText("Create Table");
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Number of Rows");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumRows, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(txtNumCols)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTable)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumRows, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumCols, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddTable)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Tables", jPanel2);

        imgURL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imgURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgURLActionPerformed(evt);
            }
        });

        imgname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imgname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgnameActionPerformed(evt);
            }
        });

        jLabel6.setText("URL");

        jLabel7.setText("Image Name");

        btnBrowse.setText("Browse Local Images");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgURL)
                            .addComponent(imgname, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                    .addComponent(btnBrowse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnAddonlineimg.setText("Add online Image");
        btnAddonlineimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddonlineimgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnAddonlineimg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddonlineimg))
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Pictures", jPanel3);

        btnBrowse1.setText("Browse for Audio File");
        btnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBrowse1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnBrowse1)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Audio", jPanel8);

        btnBrowsevideo.setText("Browse for Video File");
        btnBrowsevideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsevideoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBrowsevideo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnBrowsevideo)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Video", jPanel9);

        txtDoc.setColumns(20);
        txtDoc.setRows(5);
        jScrollPane1.setViewportView(txtDoc);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnReset.setText("Start Over");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1))
                            .addComponent(jTabbedPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Links");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtDoc.setText(boilerplate);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("My HTML", "html"));
        int retValue = chooser.showSaveDialog(this);
        if (retValue == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            try {
                FileOutputStream fos = new FileOutputStream(f.getAbsoluteFile() + ".html");
                String str = txtDoc.getText();
                fos.write(str.getBytes());
                fos.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Unable to save file.");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddlinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddlinksActionPerformed
        Object source = evt.getSource();
        if (txtDisplay.getText().length() == 0) {
            return;
        }
        try {

            sb.setLength(0);
            sb.append("\n<li>\n<a href=\"");
            sb.append(txtUrl.getText());
            sb.append("\">");
            sb.append(txtDisplay.getText());
            sb.append("</a>\n</li>\n");
            txtDoc.insert(sb.toString(), txtDoc.getText().indexOf("</ul>"));
            txtUrl.setText("");
            txtDisplay.setText("");
            //            JumpListGenerator_console console = new JumpListGenerator_console(sb);
            //
            //            console.txtDoc.insert(sb.toString(), console.txtDoc.getText().indexOf("</select>")-1);
            //            console.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "unable to insert option - missing </select>");
        }
    }//GEN-LAST:event_btnAddlinksActionPerformed

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        int num_rows = parseInt(txtNumRows.getText());
        int num_cols = parseInt(txtNumCols.getText());
        int i = 0;
        int j = 0;

        if (txtNumCols.getText().length() == 0) {
            return;
        }
        if (txtNumRows.getText().length() == 0) {
            return;
        }
        
        sb.setLength(0);
        try {
            sb.append("\n<table border=\"1\">\n<tbody>");
            for (i = 0; i < Integer.parseInt(txtNumRows.getText()); i++) {
                sb.append("\n<tr>");
                for (j = 0; j < Integer.parseInt(txtNumCols.getText()); j++) {
                    sb.append("\n<td>");
                    String tableCell = JOptionPane.showInputDialog(this, "Enter Cell Content: ");
                    sb.append(tableCell + "</td>");
                }
                sb.append("\n</tr>");
            }
            sb.append("\n</tbody>\n</table>\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "unable to insert option - missing </select>");
        }
        txtDoc.insert(sb.toString(), txtDoc.getText().indexOf("</body>"));
        txtNumCols.setText("");
        txtNumRows.setText("");
    }//GEN-LAST:event_btnAddTableActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Picture Files", "jpg", "jpeg", "gif", "png", "bmp"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("jpg File", "jpg"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("jpeg File", "jpeg"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("gif File", "gif"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("png File", "png"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("bmp File", "bmp"));
        int retValue = chooser.showOpenDialog(this);
        if (retValue == JFileChooser.APPROVE_OPTION) {
            File f2 = chooser.getSelectedFile();
            try {
                FileInputStream fos = new FileInputStream(f2);
                String str = f2.getAbsolutePath();

                sb.setLength(0);
                sb.append("\n<div>\n<img src=\"");
                sb.append(str);
                sb.append("\" alt=\"\"/>");
                sb.append("\n</div>\n");
                //                JOptionPane.showMessageDialog(this, sb);
                txtDoc.insert(sb.toString(), txtDoc.getText().indexOf("pics")+6);

                fos.close();

                //                JumpListGenerator_console console = new JumpListGenerator_console(sb);
                //
                //                console.txtDoc.insert(sb.toString(), console.txtDoc.getText().indexOf("\n</body>")-1);
                //                console.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Unable to save file.");
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowse1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser1 = new JFileChooser();
        chooser1.setAcceptAllFileFilterUsed(false);
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("Audio Files", "mp3", "flac", "wav", "aiff", "aac", "ogg", "wma"));
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("mp3 File", "mp3"));
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("Audio Interchange File Format File", "aiff"));
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("flac File", "flac"));
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("WaveForm File", "wav"));
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("Advanced Audio Coding File", "aac"));
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("Vorbis File", "ogg"));
        chooser1.addChoosableFileFilter(new FileNameExtensionFilter("windows media audio File", "wma"));
        int retValue = chooser1.showOpenDialog(this);
        if (retValue == JFileChooser.APPROVE_OPTION) {
            File f2 = chooser1.getSelectedFile();
            try {
                FileInputStream fos = new FileInputStream(f2);
                String str = f2.getAbsolutePath();
                
                sb.setLength(0);
                sb.append("\n<audio controls src=\"");
                sb.append(str);
                sb.append("\"></audio>\n");
                //                JOptionPane.showMessageDialog(this, sb);
                txtDoc.insert(sb.toString(), txtDoc.getText().indexOf("\n</body>"));

                fos.close();

                //                JumpListGenerator_console console = new JumpListGenerator_console(sb);
                //
                //                console.txtDoc.insert(sb.toString(), console.txtDoc.getText().indexOf("\n</body>")-1);
                //                console.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Unable to save file.");
            }
        }
    }//GEN-LAST:event_btnBrowse1ActionPerformed

    private void btnBrowsevideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsevideoActionPerformed
        JFileChooser chooser_video = new JFileChooser();
        chooser_video.setAcceptAllFileFilterUsed(false);
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("Video Files", "mp4", "mpg", "mpeg", "avi", "flv", "wmv", "mov", "mp4", "webm", "vob", "asf"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("mp4 File", "mp3"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("mpg File", "mpg"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("mpeg File", "mpeg"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("avi File", "avi"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("flv File", "flv"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("wmv File", "wmv"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("mov File", "mov"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("mp4 File", "mp4"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("webm File", "webm"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("vob File", "vob"));
        chooser_video.addChoosableFileFilter(new FileNameExtensionFilter("asf File", "asf"));

        int retValue = chooser_video.showOpenDialog(this);
        if (retValue == JFileChooser.APPROVE_OPTION) {
            File f2 = chooser_video.getSelectedFile();
            try {
                FileInputStream fos = new FileInputStream(f2);
                String str = f2.getAbsolutePath();
                
                sb.setLength(0);
                sb.append("\n<video controls src=\"");
                sb.append(str);
                sb.append("\"></video>\n");
                //                JOptionPane.showMessageDialog(this, sb);
                txtDoc.insert(sb.toString(), txtDoc.getText().indexOf("\n</body>"));

                fos.close();

                //                JumpListGenerator_console console = new JumpListGenerator_console(sb);
                //
                //                console.txtDoc.insert(sb.toString(), console.txtDoc.getText().indexOf("\n</body>")-1);
                //                console.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Unable to save file.");
            }
        }
    }//GEN-LAST:event_btnBrowsevideoActionPerformed

    private void btnAddtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtitleActionPerformed
        Object source = evt.getSource();
        if (txtTitle.getText().length() == 0) {
            return;
        }
        try {

            sb.setLength(0);
            sb.append("\n<h1>");
            sb.append(txtTitle.getText());
            sb.append("</h1>\n");
            JOptionPane.showMessageDialog(this, sb);
            txtDoc.insert(sb.toString(), txtDoc.getText().indexOf("</head>\n"));          
            txtTitle.setText("");
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "unable to insert option - missing </select>");
        }
    }//GEN-LAST:event_btnAddtitleActionPerformed

    private void imgURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgURLActionPerformed

    private void imgnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgnameActionPerformed

    private void btnAddonlineimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddonlineimgActionPerformed
        Object source = evt.getSource();
        if (imgURL.getText().length() == 0) {
            return;
        }
        try {

            sb.setLength(0);
            sb.append("\n<image src=\"");
            sb.append(imgURL.getText());
            sb.append("/");
            sb.append(imgname.getText());
            sb.append("\"/>\n");
            txtDoc.insert(sb.toString(), txtDoc.getText().indexOf("</body>"));
            txtUrl.setText("");
            txtDisplay.setText("");
            //            JumpListGenerator_console console = new JumpListGenerator_console(sb);
            //
            //            console.txtDoc.insert(sb.toString(), console.txtDoc.getText().indexOf("</select>")-1);
            //            console.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "unable to insert option - missing </select>");
        }
    }//GEN-LAST:event_btnAddonlineimgActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegratedJumplistGeneratorVer69.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegratedJumplistGeneratorVer69.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegratedJumplistGeneratorVer69.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegratedJumplistGeneratorVer69.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegratedJumplistGeneratorVer69().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnAddlinks;
    private javax.swing.JButton btnAddonlineimg;
    private javax.swing.JButton btnAddtitle;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnBrowse1;
    private javax.swing.JButton btnBrowsevideo;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField imgURL;
    private javax.swing.JTextField imgname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextArea txtDoc;
    private javax.swing.JTextField txtNumCols;
    private javax.swing.JTextField txtNumRows;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
